server:
  port: 8086
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Aakashrathod9617/microservice
          clone-on-start: true